development:
  adapter: postgresql
  encoding: utf8
  database: unr_transportation_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: unr_transportation_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: unr_transportation_production
  pool: 5
  username:
  password:
